### PR TITLE
inherit twig globals

### PR DESCRIPTION
**Pull request by Onefivefournine**
This pull request will allow to pass globals from twig and also to pass app variable as it passed to twig (in case if it was somehow changed). It will simplify migration from twig to pug.

### CODE REVIEW

**Review by kylekatarnls — DISMISSED** [review]
This PR make tests fail for app.token on Symfony 3.3+:
https://travis-ci.org/pug-php/pug-symfony/jobs/490449684

Because the token storage is no longer passed to AppVariable:
```php
if ($container->has('security.token_storage')) {
    $app->setTokenStorage($container->get('security.token_storage'));
}
```

I'm OK to copy all globals from Twig, but all settings applied to `AppVariable` must be kept, please restore:
```php
$app->setDebug($kernel->isDebug());
$app->setEnvironment($environment);
$app->setRequestStack($container->get('request_stack'));
// @codeCoverageIgnoreStart
if ($container->has('security.token_storage')) {
    $app->setTokenStorage($container->get('security.token_storage'));
}
```

It can be inside your loop in a `if ($globalValue instanceof AppVariable) {}`

**Comment by Onefivefournine** [comment]
Hmm, I checked on Symfony 4.2, and tokenStorage was passed, so I decided to remove it.
Ok I will return it

**Comment by kylekatarnls** [comment]
It's OK, I added it.

**Comment by Onefivefournine** [comment]
I see, thanks for replying so quickly!

**Comment by kylekatarnls** [comment]
Waiting for Travis. Will be merged if tests pass in every versions.

**Pull request merged**
